language: C
dist: trusty

before_install:
  
  # Importent Build-Config
  - export DEVICE=j23g
  - export TCLINK=https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8
  - export OFOLDER=$PWD/arch/arm/boot
  ##
  - git clone $TCLINK toolchain
  - export CROSS_COMPILE=$PWD/toolchain/bin/arm-eabi-
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential kernel-package libncurses5-dev bzip2 curl

# we're not installing anything

install: true

script:
  - export KBUILD_BUILD_USER=Parthib-K24
  - export KBUILD_BUILD_HOST=travis
  # compiling commands (main)
  - make j23g-dt_defconfig
  - make 2>> $OFOLDER/zEWlog_$(date +%b-%d-%Y-%H:%M).txt
  # this part uploads output to a cloud
  - cd $OFOLDER
  - zip Kernel_$DEVICE-$(date +%b-%d-%Y-%H:%M).zip z*
  - echo "Uploading Output" && curl --upload-file Kernel* https://transfer.sh

deploy:
  provider: releases
  file: "$OFOLDER/zImage"
  skip_cleanup: true
  on:
    tags: true
all_branches: true
